// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameMsg {

  /// <summary>Holder for reflection information generated from Common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxDb21tb24ucHJvdG8SB0dhbWVNc2ciiQEKDVNlcnZlck1lc3NhZ2USMQoP",
            "U2VydmVyQmVoYXZpb3VyGAEgASgOMhguR2FtZU1zZy5TRVJWRVJCRUhBVklP",
            "VVISEwoLVm9sdW1lVmFsdWUYAiABKAUSEAoIR2FtZU5hbWUYAyABKAkSCgoC",
            "T24YBCABKAgSEgoKQ291cnNlTGlzdBgFIAMoCSJ1CgxVbml0eU1lc3NhZ2US",
            "KwoMVW5pdHlNU0d0eXBlGAEgASgOMhUuR2FtZU1zZy5VTklUWU1TR1RZUEUS",
            "JQoJVW5pdHlEYXRhGAIgASgLMhIuR2FtZU1zZy5Vbml0eURhdGESEQoJT3Bl",
            "cmF0aW9uGAMgASgJInIKCVVuaXR5RGF0YRISCgpTcGVjaWZ5aW5nGAEgASgJ",
            "EiAKB1BlcnNvbnMYAiADKAsyDy5HYW1lTXNnLlBlcnNvbhIeCgZCbG9ja3MY",
            "AyADKAsyDi5HYW1lTXNnLkJsb2NrEg8KB0RlZmF1bHQYBCABKAkiVQoGUGVy",
            "c29uEgwKBE5hbWUYASABKAkSCwoDTnVtGAIgASgFEgsKA1VSTBgDIAEoCRIj",
            "CglBYmlsaXRpZXMYBCADKAsyEC5HYW1lTXNnLkFiaWxpdHkiLQoHQWJpbGl0",
            "eRITCgtBYmlsaXR5bmFtZRgBIAEoCRINCgVWYWx1ZRgCIAEoAiKEAQoFQmxv",
            "Y2sSDAoETmFtZRgBIAEoCRINCgVJbmRleBgCIAEoBRIqCgxCbG9ja0NvbHVt",
            "bnMYAyADKAsyFC5HYW1lTXNnLkJsb2NrQ29sdW1uEjIKEEJsb2NrQ29sdW1u",
            "RGF0YXMYBCADKAsyGC5HYW1lTXNnLkJsb2NrQ29sdW1uRGF0YSKHAQoLQmxv",
            "Y2tDb2x1bW4SDAoETmFtZRgBIAEoCRIMCgRUeXBlGAIgASgJEgwKBFNvcnQY",
            "AyABKAkSDAoEU2hvdxgEIAEoCBIOCgZTdWZmaXgYBSABKAkSEQoJQ291bnRN",
            "b2RlGAYgASgJEh0KFUNvdW50Q29sdW1EYXRhQnlJbmRleBgHIAEoBSI4Cg9C",
            "bG9ja0NvbHVtbkRhdGESEgoKQ29sdW1uRGF0YRgBIAEoCRIRCglTZXBhcmF0",
            "b3IYAiABKAki1AEKB01FU1NBR0USIQoHTVNHdHlwZRgBIAEoDjIQLkdhbWVN",
            "c2cuTVNHVFlQRRIrCgxVbml0eU1lc3NhZ2UYAiABKAsyFS5HYW1lTXNnLlVu",
            "aXR5TWVzc2FnZRItCg1TZXJ2ZXJNZXNzYWdlGAMgASgLMhYuR2FtZU1zZy5T",
            "ZXJ2ZXJNZXNzYWdlEiUKCU1TR3N0YXR1cxgEIAEoCzISLkdhbWVNc2cuTVNH",
            "U3RhdHVzEiMKCEVjaG9EYXRhGAUgASgLMhEuR2FtZU1zZy5FY2hvRGF0YSJa",
            "CglNU0dTdGF0dXMSMQoPb3BlcmF0aW9uc3RhdHVzGAEgASgOMhguR2FtZU1z",
            "Zy5PcGVyYXRpb25TdGF0dXMSDAoEU1FJRBgCIAEoBRIMCgRJbmZvGAMgASgJ",
            "IkIKCEVjaG9EYXRhEiUKCUNsaWVudEVuZBgBIAEoDjISLkdhbWVNc2cuQ0xJ",
            "RU5URU5EEg8KB0VjaG9tc2cYAiABKAkqcAoHTVNHVFlQRRIRCg1TZXJ2ZXJS",
            "ZXF1ZXN0EAASEAoMVW5pdHlSZXF1ZXN0EAESEgoOU2VydmVyUmVzcG9uc2UQ",
            "AhIRCg1Vbml0eVJlc3BvbnNlEAMSDQoJSGVhcnRFY2hvEAQSCgoGU3RhdHVz",
            "EAUqJwoMVU5JVFlNU0dUWVBFEg0KCU9wZXJhdGlvbhAAEggKBERhdGEQASo+",
            "Cg9TRVJWRVJCRUhBVklPVVISDwoLQXBwbGljYXRpb24QABIKCgZWb2x1bWUQ",
            "ARIOCgpDb3Vyc2VMaXN0EAIqkgEKD09wZXJhdGlvblN0YXR1cxITCg9OdWxs",
            "VW5pdHlDbGllbnQQABISCg5OdWxsaVBhZENsaWVudBABEg4KCk51bGxDb3Vy",
            "c2UQAhIXChNDb3Vyc2VQbGF5aXNSdW5uaW5nEAMSFgoSRGF0YWZvcm1hdHRl",
            "ckVycm9yEAQSFQoRRGF0YVRyYW5zZmVyRXJyb3IQBSoiCglDTElFTlRFTkQS",
            "CAoEV0FMTBAAEgsKB0Rlc2t0b3AQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameMsg.MSGTYPE), typeof(global::GameMsg.UNITYMSGTYPE), typeof(global::GameMsg.SERVERBEHAVIOUR), typeof(global::GameMsg.OperationStatus), typeof(global::GameMsg.CLIENTEND), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.ServerMessage), global::GameMsg.ServerMessage.Parser, new[]{ "ServerBehaviour", "VolumeValue", "GameName", "On", "CourseList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.UnityMessage), global::GameMsg.UnityMessage.Parser, new[]{ "UnityMSGtype", "UnityData", "Operation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.UnityData), global::GameMsg.UnityData.Parser, new[]{ "Specifying", "Persons", "Blocks", "Default" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.Person), global::GameMsg.Person.Parser, new[]{ "Name", "Num", "URL", "Abilities" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.Ability), global::GameMsg.Ability.Parser, new[]{ "Abilityname", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.Block), global::GameMsg.Block.Parser, new[]{ "Name", "Index", "BlockColumns", "BlockColumnDatas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.BlockColumn), global::GameMsg.BlockColumn.Parser, new[]{ "Name", "Type", "Sort", "Show", "Suffix", "CountMode", "CountColumDataByIndex" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.BlockColumnData), global::GameMsg.BlockColumnData.Parser, new[]{ "ColumnData", "Separator" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.MESSAGE), global::GameMsg.MESSAGE.Parser, new[]{ "MSGtype", "UnityMessage", "ServerMessage", "MSGstatus", "EchoData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.MSGStatus), global::GameMsg.MSGStatus.Parser, new[]{ "Operationstatus", "SQID", "Info" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMsg.EchoData), global::GameMsg.EchoData.Parser, new[]{ "ClientEnd", "Echomsg" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///---------------数据包根据客户端的种类 --------------------
  /// </summary>
  public enum MSGTYPE {
    /// <summary>
    ///---------------iPAD --------------------
    /// </summary>
    [pbr::OriginalName("ServerRequest")] ServerRequest = 0,
    [pbr::OriginalName("UnityRequest")] UnityRequest = 1,
    [pbr::OriginalName("ServerResponse")] ServerResponse = 2,
    [pbr::OriginalName("UnityResponse")] UnityResponse = 3,
    [pbr::OriginalName("HeartEcho")] HeartEcho = 4,
    [pbr::OriginalName("Status")] Status = 5,
  }

  public enum UNITYMSGTYPE {
    [pbr::OriginalName("Operation")] Operation = 0,
    [pbr::OriginalName("Data")] Data = 1,
  }

  public enum SERVERBEHAVIOUR {
    [pbr::OriginalName("Application")] Application = 0,
    [pbr::OriginalName("Volume")] Volume = 1,
    [pbr::OriginalName("CourseList")] CourseList = 2,
  }

  public enum OperationStatus {
    [pbr::OriginalName("NullUnityClient")] NullUnityClient = 0,
    [pbr::OriginalName("NulliPadClient")] NulliPadClient = 1,
    [pbr::OriginalName("NullCourse")] NullCourse = 2,
    [pbr::OriginalName("CoursePlayisRunning")] CoursePlayisRunning = 3,
    [pbr::OriginalName("DataformatterError")] DataformatterError = 4,
    [pbr::OriginalName("DataTransferError")] DataTransferError = 5,
  }

  public enum CLIENTEND {
    [pbr::OriginalName("WALL")] Wall = 0,
    [pbr::OriginalName("Desktop")] Desktop = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  ///--------------- 与方果控制台交换的包 --------------------
  /// </summary>
  public sealed partial class ServerMessage : pb::IMessage<ServerMessage> {
    private static readonly pb::MessageParser<ServerMessage> _parser = new pb::MessageParser<ServerMessage>(() => new ServerMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerMessage(ServerMessage other) : this() {
      serverBehaviour_ = other.serverBehaviour_;
      volumeValue_ = other.volumeValue_;
      gameName_ = other.gameName_;
      on_ = other.on_;
      courseList_ = other.courseList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerMessage Clone() {
      return new ServerMessage(this);
    }

    /// <summary>Field number for the "ServerBehaviour" field.</summary>
    public const int ServerBehaviourFieldNumber = 1;
    private global::GameMsg.SERVERBEHAVIOUR serverBehaviour_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.SERVERBEHAVIOUR ServerBehaviour {
      get { return serverBehaviour_; }
      set {
        serverBehaviour_ = value;
      }
    }

    /// <summary>Field number for the "VolumeValue" field.</summary>
    public const int VolumeValueFieldNumber = 2;
    private int volumeValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int VolumeValue {
      get { return volumeValue_; }
      set {
        volumeValue_ = value;
      }
    }

    /// <summary>Field number for the "GameName" field.</summary>
    public const int GameNameFieldNumber = 3;
    private string gameName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GameName {
      get { return gameName_; }
      set {
        gameName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "On" field.</summary>
    public const int OnFieldNumber = 4;
    private bool on_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool On {
      get { return on_; }
      set {
        on_ = value;
      }
    }

    /// <summary>Field number for the "CourseList" field.</summary>
    public const int CourseListFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_courseList_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> courseList_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> CourseList {
      get { return courseList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerBehaviour != other.ServerBehaviour) return false;
      if (VolumeValue != other.VolumeValue) return false;
      if (GameName != other.GameName) return false;
      if (On != other.On) return false;
      if(!courseList_.Equals(other.courseList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerBehaviour != 0) hash ^= ServerBehaviour.GetHashCode();
      if (VolumeValue != 0) hash ^= VolumeValue.GetHashCode();
      if (GameName.Length != 0) hash ^= GameName.GetHashCode();
      if (On != false) hash ^= On.GetHashCode();
      hash ^= courseList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServerBehaviour != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ServerBehaviour);
      }
      if (VolumeValue != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(VolumeValue);
      }
      if (GameName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GameName);
      }
      if (On != false) {
        output.WriteRawTag(32);
        output.WriteBool(On);
      }
      courseList_.WriteTo(output, _repeated_courseList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServerBehaviour != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ServerBehaviour);
      }
      if (VolumeValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VolumeValue);
      }
      if (GameName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameName);
      }
      if (On != false) {
        size += 1 + 1;
      }
      size += courseList_.CalculateSize(_repeated_courseList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerMessage other) {
      if (other == null) {
        return;
      }
      if (other.ServerBehaviour != 0) {
        ServerBehaviour = other.ServerBehaviour;
      }
      if (other.VolumeValue != 0) {
        VolumeValue = other.VolumeValue;
      }
      if (other.GameName.Length != 0) {
        GameName = other.GameName;
      }
      if (other.On != false) {
        On = other.On;
      }
      courseList_.Add(other.courseList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            serverBehaviour_ = (global::GameMsg.SERVERBEHAVIOUR) input.ReadEnum();
            break;
          }
          case 16: {
            VolumeValue = input.ReadInt32();
            break;
          }
          case 26: {
            GameName = input.ReadString();
            break;
          }
          case 32: {
            On = input.ReadBool();
            break;
          }
          case 42: {
            courseList_.AddEntriesFrom(input, _repeated_courseList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class UnityMessage : pb::IMessage<UnityMessage> {
    private static readonly pb::MessageParser<UnityMessage> _parser = new pb::MessageParser<UnityMessage>(() => new UnityMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityMessage(UnityMessage other) : this() {
      unityMSGtype_ = other.unityMSGtype_;
      UnityData = other.unityData_ != null ? other.UnityData.Clone() : null;
      operation_ = other.operation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityMessage Clone() {
      return new UnityMessage(this);
    }

    /// <summary>Field number for the "UnityMSGtype" field.</summary>
    public const int UnityMSGtypeFieldNumber = 1;
    private global::GameMsg.UNITYMSGTYPE unityMSGtype_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.UNITYMSGTYPE UnityMSGtype {
      get { return unityMSGtype_; }
      set {
        unityMSGtype_ = value;
      }
    }

    /// <summary>Field number for the "UnityData" field.</summary>
    public const int UnityDataFieldNumber = 2;
    private global::GameMsg.UnityData unityData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.UnityData UnityData {
      get { return unityData_; }
      set {
        unityData_ = value;
      }
    }

    /// <summary>Field number for the "Operation" field.</summary>
    public const int OperationFieldNumber = 3;
    private string operation_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Operation {
      get { return operation_; }
      set {
        operation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UnityMSGtype != other.UnityMSGtype) return false;
      if (!object.Equals(UnityData, other.UnityData)) return false;
      if (Operation != other.Operation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UnityMSGtype != 0) hash ^= UnityMSGtype.GetHashCode();
      if (unityData_ != null) hash ^= UnityData.GetHashCode();
      if (Operation.Length != 0) hash ^= Operation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UnityMSGtype != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) UnityMSGtype);
      }
      if (unityData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UnityData);
      }
      if (Operation.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Operation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UnityMSGtype != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnityMSGtype);
      }
      if (unityData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnityData);
      }
      if (Operation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Operation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityMessage other) {
      if (other == null) {
        return;
      }
      if (other.UnityMSGtype != 0) {
        UnityMSGtype = other.UnityMSGtype;
      }
      if (other.unityData_ != null) {
        if (unityData_ == null) {
          unityData_ = new global::GameMsg.UnityData();
        }
        UnityData.MergeFrom(other.UnityData);
      }
      if (other.Operation.Length != 0) {
        Operation = other.Operation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            unityMSGtype_ = (global::GameMsg.UNITYMSGTYPE) input.ReadEnum();
            break;
          }
          case 18: {
            if (unityData_ == null) {
              unityData_ = new global::GameMsg.UnityData();
            }
            input.ReadMessage(unityData_);
            break;
          }
          case 26: {
            Operation = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///-------未知的数据，需要iPad端解析-------
  /// </summary>
  public sealed partial class UnityData : pb::IMessage<UnityData> {
    private static readonly pb::MessageParser<UnityData> _parser = new pb::MessageParser<UnityData>(() => new UnityData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityData(UnityData other) : this() {
      specifying_ = other.specifying_;
      persons_ = other.persons_.Clone();
      blocks_ = other.blocks_.Clone();
      default_ = other.default_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityData Clone() {
      return new UnityData(this);
    }

    /// <summary>Field number for the "Specifying" field.</summary>
    public const int SpecifyingFieldNumber = 1;
    private string specifying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Specifying {
      get { return specifying_; }
      set {
        specifying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Persons" field.</summary>
    public const int PersonsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::GameMsg.Person> _repeated_persons_codec
        = pb::FieldCodec.ForMessage(18, global::GameMsg.Person.Parser);
    private readonly pbc::RepeatedField<global::GameMsg.Person> persons_ = new pbc::RepeatedField<global::GameMsg.Person>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameMsg.Person> Persons {
      get { return persons_; }
    }

    /// <summary>Field number for the "Blocks" field.</summary>
    public const int BlocksFieldNumber = 3;
    private static readonly pb::FieldCodec<global::GameMsg.Block> _repeated_blocks_codec
        = pb::FieldCodec.ForMessage(26, global::GameMsg.Block.Parser);
    private readonly pbc::RepeatedField<global::GameMsg.Block> blocks_ = new pbc::RepeatedField<global::GameMsg.Block>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameMsg.Block> Blocks {
      get { return blocks_; }
    }

    /// <summary>Field number for the "Default" field.</summary>
    public const int DefaultFieldNumber = 4;
    private string default_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Default {
      get { return default_; }
      set {
        default_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Specifying != other.Specifying) return false;
      if(!persons_.Equals(other.persons_)) return false;
      if(!blocks_.Equals(other.blocks_)) return false;
      if (Default != other.Default) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Specifying.Length != 0) hash ^= Specifying.GetHashCode();
      hash ^= persons_.GetHashCode();
      hash ^= blocks_.GetHashCode();
      if (Default.Length != 0) hash ^= Default.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Specifying.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Specifying);
      }
      persons_.WriteTo(output, _repeated_persons_codec);
      blocks_.WriteTo(output, _repeated_blocks_codec);
      if (Default.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Default);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Specifying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Specifying);
      }
      size += persons_.CalculateSize(_repeated_persons_codec);
      size += blocks_.CalculateSize(_repeated_blocks_codec);
      if (Default.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Default);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityData other) {
      if (other == null) {
        return;
      }
      if (other.Specifying.Length != 0) {
        Specifying = other.Specifying;
      }
      persons_.Add(other.persons_);
      blocks_.Add(other.blocks_);
      if (other.Default.Length != 0) {
        Default = other.Default;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Specifying = input.ReadString();
            break;
          }
          case 18: {
            persons_.AddEntriesFrom(input, _repeated_persons_codec);
            break;
          }
          case 26: {
            blocks_.AddEntriesFrom(input, _repeated_blocks_codec);
            break;
          }
          case 34: {
            Default = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Person : pb::IMessage<Person> {
    private static readonly pb::MessageParser<Person> _parser = new pb::MessageParser<Person>(() => new Person());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Person> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Person() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Person(Person other) : this() {
      name_ = other.name_;
      num_ = other.num_;
      uRL_ = other.uRL_;
      abilities_ = other.abilities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Person Clone() {
      return new Person(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    /// <summary>Field number for the "URL" field.</summary>
    public const int URLFieldNumber = 3;
    private string uRL_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string URL {
      get { return uRL_; }
      set {
        uRL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Abilities" field.</summary>
    public const int AbilitiesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::GameMsg.Ability> _repeated_abilities_codec
        = pb::FieldCodec.ForMessage(34, global::GameMsg.Ability.Parser);
    private readonly pbc::RepeatedField<global::GameMsg.Ability> abilities_ = new pbc::RepeatedField<global::GameMsg.Ability>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameMsg.Ability> Abilities {
      get { return abilities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Person);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Person other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Num != other.Num) return false;
      if (URL != other.URL) return false;
      if(!abilities_.Equals(other.abilities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (URL.Length != 0) hash ^= URL.GetHashCode();
      hash ^= abilities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
      if (URL.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(URL);
      }
      abilities_.WriteTo(output, _repeated_abilities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (URL.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(URL);
      }
      size += abilities_.CalculateSize(_repeated_abilities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Person other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      if (other.URL.Length != 0) {
        URL = other.URL;
      }
      abilities_.Add(other.abilities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
          case 26: {
            URL = input.ReadString();
            break;
          }
          case 34: {
            abilities_.AddEntriesFrom(input, _repeated_abilities_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Ability : pb::IMessage<Ability> {
    private static readonly pb::MessageParser<Ability> _parser = new pb::MessageParser<Ability>(() => new Ability());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Ability> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ability() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ability(Ability other) : this() {
      abilityname_ = other.abilityname_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ability Clone() {
      return new Ability(this);
    }

    /// <summary>Field number for the "Abilityname" field.</summary>
    public const int AbilitynameFieldNumber = 1;
    private string abilityname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Abilityname {
      get { return abilityname_; }
      set {
        abilityname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Value" field.</summary>
    public const int ValueFieldNumber = 2;
    private float value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Ability);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Ability other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Abilityname != other.Abilityname) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Value, other.Value)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Abilityname.Length != 0) hash ^= Abilityname.GetHashCode();
      if (Value != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Value);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Abilityname.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Abilityname);
      }
      if (Value != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Abilityname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Abilityname);
      }
      if (Value != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Ability other) {
      if (other == null) {
        return;
      }
      if (other.Abilityname.Length != 0) {
        Abilityname = other.Abilityname;
      }
      if (other.Value != 0F) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Abilityname = input.ReadString();
            break;
          }
          case 21: {
            Value = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///-------默认每个blockcolumn,第一个为学生的Num,防止重名，数据匹配错误-------
  /// </summary>
  public sealed partial class Block : pb::IMessage<Block> {
    private static readonly pb::MessageParser<Block> _parser = new pb::MessageParser<Block>(() => new Block());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Block> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Block() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Block(Block other) : this() {
      name_ = other.name_;
      index_ = other.index_;
      blockColumns_ = other.blockColumns_.Clone();
      blockColumnDatas_ = other.blockColumnDatas_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Block Clone() {
      return new Block(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Index" field.</summary>
    public const int IndexFieldNumber = 2;
    private int index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "BlockColumns" field.</summary>
    public const int BlockColumnsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::GameMsg.BlockColumn> _repeated_blockColumns_codec
        = pb::FieldCodec.ForMessage(26, global::GameMsg.BlockColumn.Parser);
    private readonly pbc::RepeatedField<global::GameMsg.BlockColumn> blockColumns_ = new pbc::RepeatedField<global::GameMsg.BlockColumn>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameMsg.BlockColumn> BlockColumns {
      get { return blockColumns_; }
    }

    /// <summary>Field number for the "BlockColumnDatas" field.</summary>
    public const int BlockColumnDatasFieldNumber = 4;
    private static readonly pb::FieldCodec<global::GameMsg.BlockColumnData> _repeated_blockColumnDatas_codec
        = pb::FieldCodec.ForMessage(34, global::GameMsg.BlockColumnData.Parser);
    private readonly pbc::RepeatedField<global::GameMsg.BlockColumnData> blockColumnDatas_ = new pbc::RepeatedField<global::GameMsg.BlockColumnData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameMsg.BlockColumnData> BlockColumnDatas {
      get { return blockColumnDatas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Block);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Block other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Index != other.Index) return false;
      if(!blockColumns_.Equals(other.blockColumns_)) return false;
      if(!blockColumnDatas_.Equals(other.blockColumnDatas_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Index != 0) hash ^= Index.GetHashCode();
      hash ^= blockColumns_.GetHashCode();
      hash ^= blockColumnDatas_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Index != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Index);
      }
      blockColumns_.WriteTo(output, _repeated_blockColumns_codec);
      blockColumnDatas_.WriteTo(output, _repeated_blockColumnDatas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
      }
      size += blockColumns_.CalculateSize(_repeated_blockColumns_codec);
      size += blockColumnDatas_.CalculateSize(_repeated_blockColumnDatas_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Block other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      blockColumns_.Add(other.blockColumns_);
      blockColumnDatas_.Add(other.blockColumnDatas_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Index = input.ReadInt32();
            break;
          }
          case 26: {
            blockColumns_.AddEntriesFrom(input, _repeated_blockColumns_codec);
            break;
          }
          case 34: {
            blockColumnDatas_.AddEntriesFrom(input, _repeated_blockColumnDatas_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class BlockColumn : pb::IMessage<BlockColumn> {
    private static readonly pb::MessageParser<BlockColumn> _parser = new pb::MessageParser<BlockColumn>(() => new BlockColumn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BlockColumn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockColumn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockColumn(BlockColumn other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      sort_ = other.sort_;
      show_ = other.show_;
      suffix_ = other.suffix_;
      countMode_ = other.countMode_;
      countColumDataByIndex_ = other.countColumDataByIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockColumn Clone() {
      return new BlockColumn(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 2;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sort" field.</summary>
    public const int SortFieldNumber = 3;
    private string sort_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sort {
      get { return sort_; }
      set {
        sort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Show" field.</summary>
    public const int ShowFieldNumber = 4;
    private bool show_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Show {
      get { return show_; }
      set {
        show_ = value;
      }
    }

    /// <summary>Field number for the "Suffix" field.</summary>
    public const int SuffixFieldNumber = 5;
    private string suffix_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Suffix {
      get { return suffix_; }
      set {
        suffix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CountMode" field.</summary>
    public const int CountModeFieldNumber = 6;
    private string countMode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CountMode {
      get { return countMode_; }
      set {
        countMode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CountColumDataByIndex" field.</summary>
    public const int CountColumDataByIndexFieldNumber = 7;
    private int countColumDataByIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CountColumDataByIndex {
      get { return countColumDataByIndex_; }
      set {
        countColumDataByIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BlockColumn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BlockColumn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (Sort != other.Sort) return false;
      if (Show != other.Show) return false;
      if (Suffix != other.Suffix) return false;
      if (CountMode != other.CountMode) return false;
      if (CountColumDataByIndex != other.CountColumDataByIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (Sort.Length != 0) hash ^= Sort.GetHashCode();
      if (Show != false) hash ^= Show.GetHashCode();
      if (Suffix.Length != 0) hash ^= Suffix.GetHashCode();
      if (CountMode.Length != 0) hash ^= CountMode.GetHashCode();
      if (CountColumDataByIndex != 0) hash ^= CountColumDataByIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Type);
      }
      if (Sort.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Sort);
      }
      if (Show != false) {
        output.WriteRawTag(32);
        output.WriteBool(Show);
      }
      if (Suffix.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Suffix);
      }
      if (CountMode.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CountMode);
      }
      if (CountColumDataByIndex != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(CountColumDataByIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (Sort.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sort);
      }
      if (Show != false) {
        size += 1 + 1;
      }
      if (Suffix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Suffix);
      }
      if (CountMode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountMode);
      }
      if (CountColumDataByIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CountColumDataByIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BlockColumn other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.Sort.Length != 0) {
        Sort = other.Sort;
      }
      if (other.Show != false) {
        Show = other.Show;
      }
      if (other.Suffix.Length != 0) {
        Suffix = other.Suffix;
      }
      if (other.CountMode.Length != 0) {
        CountMode = other.CountMode;
      }
      if (other.CountColumDataByIndex != 0) {
        CountColumDataByIndex = other.CountColumDataByIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Type = input.ReadString();
            break;
          }
          case 26: {
            Sort = input.ReadString();
            break;
          }
          case 32: {
            Show = input.ReadBool();
            break;
          }
          case 42: {
            Suffix = input.ReadString();
            break;
          }
          case 50: {
            CountMode = input.ReadString();
            break;
          }
          case 56: {
            CountColumDataByIndex = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BlockColumnData : pb::IMessage<BlockColumnData> {
    private static readonly pb::MessageParser<BlockColumnData> _parser = new pb::MessageParser<BlockColumnData>(() => new BlockColumnData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BlockColumnData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockColumnData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockColumnData(BlockColumnData other) : this() {
      columnData_ = other.columnData_;
      separator_ = other.separator_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockColumnData Clone() {
      return new BlockColumnData(this);
    }

    /// <summary>Field number for the "ColumnData" field.</summary>
    public const int ColumnDataFieldNumber = 1;
    private string columnData_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ColumnData {
      get { return columnData_; }
      set {
        columnData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Separator" field.</summary>
    public const int SeparatorFieldNumber = 2;
    private string separator_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Separator {
      get { return separator_; }
      set {
        separator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BlockColumnData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BlockColumnData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ColumnData != other.ColumnData) return false;
      if (Separator != other.Separator) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ColumnData.Length != 0) hash ^= ColumnData.GetHashCode();
      if (Separator.Length != 0) hash ^= Separator.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ColumnData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ColumnData);
      }
      if (Separator.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Separator);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ColumnData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ColumnData);
      }
      if (Separator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Separator);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BlockColumnData other) {
      if (other == null) {
        return;
      }
      if (other.ColumnData.Length != 0) {
        ColumnData = other.ColumnData;
      }
      if (other.Separator.Length != 0) {
        Separator = other.Separator;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ColumnData = input.ReadString();
            break;
          }
          case 18: {
            Separator = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///--------------- Heart包暂时没有消息体 ------------------
  /// </summary>
  public sealed partial class MESSAGE : pb::IMessage<MESSAGE> {
    private static readonly pb::MessageParser<MESSAGE> _parser = new pb::MessageParser<MESSAGE>(() => new MESSAGE());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MESSAGE> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MESSAGE() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MESSAGE(MESSAGE other) : this() {
      mSGtype_ = other.mSGtype_;
      UnityMessage = other.unityMessage_ != null ? other.UnityMessage.Clone() : null;
      ServerMessage = other.serverMessage_ != null ? other.ServerMessage.Clone() : null;
      MSGstatus = other.mSGstatus_ != null ? other.MSGstatus.Clone() : null;
      EchoData = other.echoData_ != null ? other.EchoData.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MESSAGE Clone() {
      return new MESSAGE(this);
    }

    /// <summary>Field number for the "MSGtype" field.</summary>
    public const int MSGtypeFieldNumber = 1;
    private global::GameMsg.MSGTYPE mSGtype_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.MSGTYPE MSGtype {
      get { return mSGtype_; }
      set {
        mSGtype_ = value;
      }
    }

    /// <summary>Field number for the "UnityMessage" field.</summary>
    public const int UnityMessageFieldNumber = 2;
    private global::GameMsg.UnityMessage unityMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.UnityMessage UnityMessage {
      get { return unityMessage_; }
      set {
        unityMessage_ = value;
      }
    }

    /// <summary>Field number for the "ServerMessage" field.</summary>
    public const int ServerMessageFieldNumber = 3;
    private global::GameMsg.ServerMessage serverMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.ServerMessage ServerMessage {
      get { return serverMessage_; }
      set {
        serverMessage_ = value;
      }
    }

    /// <summary>Field number for the "MSGstatus" field.</summary>
    public const int MSGstatusFieldNumber = 4;
    private global::GameMsg.MSGStatus mSGstatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.MSGStatus MSGstatus {
      get { return mSGstatus_; }
      set {
        mSGstatus_ = value;
      }
    }

    /// <summary>Field number for the "EchoData" field.</summary>
    public const int EchoDataFieldNumber = 5;
    private global::GameMsg.EchoData echoData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.EchoData EchoData {
      get { return echoData_; }
      set {
        echoData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MESSAGE);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MESSAGE other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MSGtype != other.MSGtype) return false;
      if (!object.Equals(UnityMessage, other.UnityMessage)) return false;
      if (!object.Equals(ServerMessage, other.ServerMessage)) return false;
      if (!object.Equals(MSGstatus, other.MSGstatus)) return false;
      if (!object.Equals(EchoData, other.EchoData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MSGtype != 0) hash ^= MSGtype.GetHashCode();
      if (unityMessage_ != null) hash ^= UnityMessage.GetHashCode();
      if (serverMessage_ != null) hash ^= ServerMessage.GetHashCode();
      if (mSGstatus_ != null) hash ^= MSGstatus.GetHashCode();
      if (echoData_ != null) hash ^= EchoData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MSGtype != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MSGtype);
      }
      if (unityMessage_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UnityMessage);
      }
      if (serverMessage_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ServerMessage);
      }
      if (mSGstatus_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(MSGstatus);
      }
      if (echoData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EchoData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MSGtype != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MSGtype);
      }
      if (unityMessage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnityMessage);
      }
      if (serverMessage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerMessage);
      }
      if (mSGstatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MSGstatus);
      }
      if (echoData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EchoData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MESSAGE other) {
      if (other == null) {
        return;
      }
      if (other.MSGtype != 0) {
        MSGtype = other.MSGtype;
      }
      if (other.unityMessage_ != null) {
        if (unityMessage_ == null) {
          unityMessage_ = new global::GameMsg.UnityMessage();
        }
        UnityMessage.MergeFrom(other.UnityMessage);
      }
      if (other.serverMessage_ != null) {
        if (serverMessage_ == null) {
          serverMessage_ = new global::GameMsg.ServerMessage();
        }
        ServerMessage.MergeFrom(other.ServerMessage);
      }
      if (other.mSGstatus_ != null) {
        if (mSGstatus_ == null) {
          mSGstatus_ = new global::GameMsg.MSGStatus();
        }
        MSGstatus.MergeFrom(other.MSGstatus);
      }
      if (other.echoData_ != null) {
        if (echoData_ == null) {
          echoData_ = new global::GameMsg.EchoData();
        }
        EchoData.MergeFrom(other.EchoData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            mSGtype_ = (global::GameMsg.MSGTYPE) input.ReadEnum();
            break;
          }
          case 18: {
            if (unityMessage_ == null) {
              unityMessage_ = new global::GameMsg.UnityMessage();
            }
            input.ReadMessage(unityMessage_);
            break;
          }
          case 26: {
            if (serverMessage_ == null) {
              serverMessage_ = new global::GameMsg.ServerMessage();
            }
            input.ReadMessage(serverMessage_);
            break;
          }
          case 34: {
            if (mSGstatus_ == null) {
              mSGstatus_ = new global::GameMsg.MSGStatus();
            }
            input.ReadMessage(mSGstatus_);
            break;
          }
          case 42: {
            if (echoData_ == null) {
              echoData_ = new global::GameMsg.EchoData();
            }
            input.ReadMessage(echoData_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class MSGStatus : pb::IMessage<MSGStatus> {
    private static readonly pb::MessageParser<MSGStatus> _parser = new pb::MessageParser<MSGStatus>(() => new MSGStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MSGStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MSGStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MSGStatus(MSGStatus other) : this() {
      operationstatus_ = other.operationstatus_;
      sQID_ = other.sQID_;
      info_ = other.info_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MSGStatus Clone() {
      return new MSGStatus(this);
    }

    /// <summary>Field number for the "operationstatus" field.</summary>
    public const int OperationstatusFieldNumber = 1;
    private global::GameMsg.OperationStatus operationstatus_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.OperationStatus Operationstatus {
      get { return operationstatus_; }
      set {
        operationstatus_ = value;
      }
    }

    /// <summary>Field number for the "SQID" field.</summary>
    public const int SQIDFieldNumber = 2;
    private int sQID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SQID {
      get { return sQID_; }
      set {
        sQID_ = value;
      }
    }

    /// <summary>Field number for the "Info" field.</summary>
    public const int InfoFieldNumber = 3;
    private string info_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Info {
      get { return info_; }
      set {
        info_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MSGStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MSGStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Operationstatus != other.Operationstatus) return false;
      if (SQID != other.SQID) return false;
      if (Info != other.Info) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Operationstatus != 0) hash ^= Operationstatus.GetHashCode();
      if (SQID != 0) hash ^= SQID.GetHashCode();
      if (Info.Length != 0) hash ^= Info.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Operationstatus != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Operationstatus);
      }
      if (SQID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SQID);
      }
      if (Info.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Info);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Operationstatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operationstatus);
      }
      if (SQID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SQID);
      }
      if (Info.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Info);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MSGStatus other) {
      if (other == null) {
        return;
      }
      if (other.Operationstatus != 0) {
        Operationstatus = other.Operationstatus;
      }
      if (other.SQID != 0) {
        SQID = other.SQID;
      }
      if (other.Info.Length != 0) {
        Info = other.Info;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            operationstatus_ = (global::GameMsg.OperationStatus) input.ReadEnum();
            break;
          }
          case 16: {
            SQID = input.ReadInt32();
            break;
          }
          case 26: {
            Info = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EchoData : pb::IMessage<EchoData> {
    private static readonly pb::MessageParser<EchoData> _parser = new pb::MessageParser<EchoData>(() => new EchoData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EchoData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMsg.CommonReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EchoData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EchoData(EchoData other) : this() {
      clientEnd_ = other.clientEnd_;
      echomsg_ = other.echomsg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EchoData Clone() {
      return new EchoData(this);
    }

    /// <summary>Field number for the "ClientEnd" field.</summary>
    public const int ClientEndFieldNumber = 1;
    private global::GameMsg.CLIENTEND clientEnd_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameMsg.CLIENTEND ClientEnd {
      get { return clientEnd_; }
      set {
        clientEnd_ = value;
      }
    }

    /// <summary>Field number for the "Echomsg" field.</summary>
    public const int EchomsgFieldNumber = 2;
    private string echomsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Echomsg {
      get { return echomsg_; }
      set {
        echomsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EchoData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EchoData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientEnd != other.ClientEnd) return false;
      if (Echomsg != other.Echomsg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientEnd != 0) hash ^= ClientEnd.GetHashCode();
      if (Echomsg.Length != 0) hash ^= Echomsg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ClientEnd != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ClientEnd);
      }
      if (Echomsg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Echomsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ClientEnd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ClientEnd);
      }
      if (Echomsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Echomsg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EchoData other) {
      if (other == null) {
        return;
      }
      if (other.ClientEnd != 0) {
        ClientEnd = other.ClientEnd;
      }
      if (other.Echomsg.Length != 0) {
        Echomsg = other.Echomsg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            clientEnd_ = (global::GameMsg.CLIENTEND) input.ReadEnum();
            break;
          }
          case 18: {
            Echomsg = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
