const Map<String, Map<String, Object?>> coursesByName = <String, Map<String, Object?>>{
  'H2O的奇幻漂流': <String, Object?>{
    'name': 'H2O的奇幻漂流',
    'class': '中班',
    'describe': '社会、科学',
    'type': '人际之行',
    'letterName': 'h2odqhpl',
  },
  '万里长城': <String, Object?>{
    'name': '万里长城',
    'class': '大班',
    'describe': '社会、语言',
    'type': '人际之行',
    'letterName': 'wlcc',
  },
  '不上你的当': <String, Object?>{
    'name': '不上你的当',
    'class': '全部年级',
    'describe': '健康、社会',
    'type': '安全之盾',
    'letterName': 'bsndd',
  },
  '不同的肤色': <String, Object?>{
    'name': '不同的肤色',
    'class': '中班',
    'describe': '健康、社会',
    'type': '内省之智',
    'letterName': 'btdfs',
  },
  '不忘初心牢记使命': <String, Object?>{
    'name': '不忘初心牢记使命',
    'class': '大班',
    'describe': '社会',
    'type': '人际之行',
    'letterName': 'bwcxljsm',
  },
  '了不起的祖国': <String, Object?>{
    'name': '了不起的祖国',
    'class': '大班',
    'describe': '社会、语言',
    'type': '人际之行',
    'letterName': 'lbqdzg',
  },
  '了不起的轮子': <String, Object?>{
    'name': '了不起的轮子',
    'class': '大班',
    'describe': '科学、社会',
    'type': '智慧之力',
    'letterName': 'lbqdlz',
  },
  '五彩的端午节': <String, Object?>{
    'name': '五彩的端午节',
    'class': '中班',
    'describe': '社会',
    'type': '人际之行',
    'letterName': 'wcddwj',
  },
  '冰雪世界': <String, Object?>{
    'name': '冰雪世界',
    'class': '大班',
    'describe': '科学、艺术',
    'type': '自然之谜',
    'letterName': 'bxsj',
  },
  '凉爽的秋天': <String, Object?>{
    'name': '凉爽的秋天',
    'class': '小班',
    'describe': '健康、科学、社会',
    'type': '自然之谜',
    'letterName': 'lsdqt',
  },
  '可怕的地震': <String, Object?>{
    'name': '可怕的地震',
    'class': '全部年级',
    'describe': '健康、社会、科学',
    'type': '安全之盾',
    'letterName': 'kpddz',
  },
  '可爱的牙宝宝': <String, Object?>{
    'name': '可爱的牙宝宝',
    'class': '中班',
    'describe': '健康',
    'type': '内省之智',
    'letterName': 'kadybb',
  },
  '向大自然学本领': <String, Object?>{
    'name': '向大自然学本领',
    'class': '中班',
    'describe': '艺术、科学',
    'type': '创想之光',
    'letterName': 'xdzrxbl',
  },
  '喜气洋洋过新年': <String, Object?>{
    'name': '喜气洋洋过新年',
    'class': '小班',
    'describe': '社会、艺术、语言',
    'type': '人际之行',
    'letterName': 'xqyygxn',
  },
  '喷发的小火山': <String, Object?>{
    'name': '喷发的小火山',
    'class': '中班',
    'describe': '社会、科学',
    'type': '自然之谜',
    'letterName': 'pfdxhs',
  },
  '团团圆圆过中秋': <String, Object?>{
    'name': '团团圆圆过中秋',
    'class': '小班',
    'describe': '社会、艺术、语言',
    'type': '人际之行',
    'letterName': 'ttyygzq',
  },
  '图形变变变': <String, Object?>{
    'name': '图形变变变',
    'class': '大班',
    'describe': '科学、语言',
    'type': '智慧之力',
    'letterName': 'txbbb',
  },
  '土壤的秘密': <String, Object?>{
    'name': '土壤的秘密',
    'class': '中班',
    'describe': '科学',
    'type': '自然之谜',
    'letterName': 'trdmm',
  },
  '垃圾分类我能行': <String, Object?>{
    'name': '垃圾分类我能行',
    'class': '中班',
    'describe': '社会',
    'type': '人际之行',
    'letterName': 'ljflwnx',
  },
  '夏天真热啊': <String, Object?>{
    'name': '夏天真热啊',
    'class': '小班',
    'describe': '健康、社会',
    'type': '自然之谜',
    'letterName': 'xtzra',
  },
  '夜晚的世界': <String, Object?>{
    'name': '夜晚的世界',
    'class': '大班',
    'describe': '科学、社会',
    'type': '自然之谜',
    'letterName': 'ywdsj',
  },
  '奇妙的小雨滴': <String, Object?>{
    'name': '奇妙的小雨滴',
    'class': '小班',
    'describe': '科学、语言',
    'type': '自然之谜',
    'letterName': 'qmdxyd',
  },
  '好玩的点线面': <String, Object?>{
    'name': '好玩的点线面',
    'class': '中班',
    'describe': '社会、艺术、语言',
    'type': '创想之光',
    'letterName': 'hwddxm',
  },
  '小壁虎借尾巴': <String, Object?>{
    'name': '小壁虎借尾巴',
    'class': '中班',
    'describe': '语言',
    'type': '童梦之语',
    'letterName': 'xbhjwb',
  },
  '小小指纹真神奇': <String, Object?>{
    'name': '小小指纹真神奇',
    'class': '中班',
    'describe': '社会、科学',
    'type': '智慧之力',
    'letterName': 'xxzwzsq',
  },
  '小小收纳员': <String, Object?>{
    'name': '小小收纳员',
    'class': '小班',
    'describe': '社会、语音',
    'type': '智慧之力',
    'letterName': 'xxsny',
  },
  '小小树叶画': <String, Object?>{
    'name': '小小树叶画',
    'class': '小班',
    'describe': '社会、艺术',
    'type': '创想之光',
    'letterName': 'xxsyh',
  },
  '小小粉刷匠': <String, Object?>{
    'name': '小小粉刷匠',
    'class': '小班',
    'describe': '艺术、语言',
    'type': '创想之光',
    'letterName': 'xxfsj',
  },
  '小小超市': <String, Object?>{
    'name': '小小超市',
    'class': '大班',
    'describe': '社会、语音',
    'type': '智慧之力',
    'letterName': 'xxcs',
  },
  '小蚂蚁大智慧': <String, Object?>{
    'name': '小蚂蚁大智慧',
    'class': '大班',
    'describe': '科学、语言',
    'type': '智慧之力',
    'letterName': 'xmydzh',
  },
  '工作最光荣': <String, Object?>{
    'name': '工作最光荣',
    'class': '大班',
    'describe': '社会、语言',
    'type': '人际之行',
    'letterName': 'gzzgr',
  },
  '平衡的乐趣': <String, Object?>{
    'name': '平衡的乐趣',
    'class': '中班',
    'describe': '科学、语言',
    'type': '智慧之力',
    'letterName': 'phdlq',
  },
  '开心小庄园': <String, Object?>{
    'name': '开心小庄园',
    'class': '小班',
    'describe': '社会、语言',
    'type': '童梦之语',
    'letterName': 'kxxzy',
  },
  '我从哪里来': <String, Object?>{
    'name': '我从哪里来',
    'class': '大班',
    'describe': '健康、科学、社会',
    'type': '内省之智',
    'letterName': 'wcnll',
  },
  '我们的地球': <String, Object?>{
    'name': '我们的地球',
    'class': '大班',
    'describe': '科学、社会',
    'type': '自然之谜',
    'letterName': 'wmddq',
  },
  '我们的奥运会': <String, Object?>{
    'name': '我们的奥运会',
    'class': '中班',
    'describe': '健康、科学、社会',
    'type': '运动之星',
    'letterName': 'wmdayh',
  },
  '我是分类小能手': <String, Object?>{
    'name': '我是分类小能手',
    'class': '大班',
    'describe': '科学、社会',
    'type': '智慧之力',
    'letterName': 'wsflxns',
  },
  '我是安全小卫士': <String, Object?>{
    'name': '我是安全小卫士',
    'class': '全部年级',
    'describe': '健康、社会',
    'type': '安全之盾',
    'letterName': 'wsaqxws',
  },
  '我爱我家': <String, Object?>{
    'name': '我爱我家',
    'class': '小班',
    'describe': '社会、语言',
    'type': '人际之行',
    'letterName': 'wawj',
  },
  '我爱运动': <String, Object?>{
    'name': '我爱运动',
    'class': '中班',
    'describe': '健康、社会',
    'type': '运动之星',
    'letterName': 'wayd',
  },
  '我的时间': <String, Object?>{
    'name': '我的时间',
    'class': '大班',
    'describe': '科学、社会',
    'type': '童梦之语',
    'letterName': 'wdsj',
  },
  '我眼中的世界': <String, Object?>{
    'name': '我眼中的世界',
    'class': '小班',
    'describe': '社会、艺术、语音',
    'type': '创想之光',
    'letterName': 'wyzdsj',
  },
  '我长高了': <String, Object?>{
    'name': '我长高了',
    'class': '大班',
    'describe': '健康、科学',
    'type': '内省之智',
    'letterName': 'wzgl',
  },
  '我防溺水有高招': <String, Object?>{
    'name': '我防溺水有高招',
    'class': '全部年级',
    'describe': '健康、社会',
    'type': '安全之盾',
    'letterName': 'wfnsygz',
  },
  '探险外太空': <String, Object?>{
    'name': '探险外太空',
    'class': '大班',
    'describe': '科学',
    'type': '自然之谜',
    'letterName': 'txwtk',
  },
  '春天一起去踏青': <String, Object?>{
    'name': '春天一起去踏青',
    'class': '小班',
    'describe': '健康、科学、社会',
    'type': '自然之谜',
    'letterName': 'ctyqqtq',
  },
  '月球探秘': <String, Object?>{
    'name': '月球探秘',
    'class': '大班',
    'describe': '社会、科学',
    'type': '自然之谜',
    'letterName': 'yqtm',
  },
  '有趣的数字': <String, Object?>{
    'name': '有趣的数字',
    'class': '小班',
    'describe': '艺术、语言',
    'type': '智慧之力',
    'letterName': 'yqdsz',
  },
  '桃源蜜生活': <String, Object?>{
    'name': '桃源蜜生活',
    'class': '全部年级',
    'describe': '科学、社会',
    'type': '创想之光',
    'letterName': 'tymsh',
  },
  '森林的小秘密': <String, Object?>{
    'name': '森林的小秘密',
    'class': '小班',
    'describe': '艺术、科学',
    'type': '创想之光',
    'letterName': 'sldxmm',
  },
  '正月十五闹元宵': <String, Object?>{
    'name': '正月十五闹元宵',
    'class': '中班',
    'describe': '社会、艺术、语言',
    'type': '人际之行',
    'letterName': 'zyswnyx',
  },
  '汉字的演变': <String, Object?>{
    'name': '汉字的演变',
    'class': '大班',
    'describe': '社会、艺术、语言',
    'type': '创想之光',
    'letterName': 'hzdyb',
  },
  '沙漠探险之旅': <String, Object?>{
    'name': '沙漠探险之旅',
    'class': '中班',
    'describe': '科学',
    'type': '自然之谜',
    'letterName': 'smtxzl',
  },
  '海上历险记': <String, Object?>{
    'name': '海上历险记',
    'class': '大班',
    'describe': '社会、语言',
    'type': '童梦之语',
    'letterName': 'hslxj',
  },
  '海底世界': <String, Object?>{
    'name': '海底世界',
    'class': '小班',
    'describe': '艺术、科学',
    'type': '创想之光',
    'letterName': 'hdsj',
  },
  '特别的日子': <String, Object?>{
    'name': '特别的日子',
    'class': '小班',
    'describe': '语言、社会',
    'type': '童梦之语',
    'letterName': 'tbdrz',
  },
  '猜猜我是谁': <String, Object?>{
    'name': '猜猜我是谁',
    'class': '小班',
    'describe': '科学',
    'type': '自然之谜',
    'letterName': 'ccwss',
  },
  '疯狂马拉松': <String, Object?>{
    'name': '疯狂马拉松',
    'class': '大班',
    'describe': '健康、社会',
    'type': '运动之星',
    'letterName': 'fkmls',
  },
  '白色污染危害大': <String, Object?>{
    'name': '白色污染危害大',
    'class': '中班',
    'describe': '社会、科学',
    'type': '人际之行',
    'letterName': 'bswrwhd',
  },
  '真的有恐龙吗': <String, Object?>{
    'name': '真的有恐龙吗',
    'class': '中班',
    'describe': '科学、语言',
    'type': '自然之谜',
    'letterName': 'zdyklm',
  },
  '神奇的乐器': <String, Object?>{
    'name': '神奇的乐器',
    'class': '大班',
    'describe': '艺术',
    'type': '音乐之声',
    'letterName': 'sqdyq',
  },
  '神奇的叶子': <String, Object?>{
    'name': '神奇的叶子',
    'class': '大班',
    'describe': '科学',
    'type': '自然之谜',
    'letterName': 'sqdyz',
  },
  '神奇的食物链': <String, Object?>{
    'name': '神奇的食物链',
    'class': '大班',
    'describe': '科学、社会',
    'type': '自然之谜',
    'letterName': 'sqdswl',
  },
  '种子在哪里': <String, Object?>{
    'name': '种子在哪里',
    'class': '中班',
    'describe': '社会、科学',
    'type': '自然之谜',
    'letterName': 'zzznl',
  },
  '空间与方向': <String, Object?>{
    'name': '空间与方向',
    'class': '大班',
    'describe': '社会、艺术、语言',
    'type': '创想之光',
    'letterName': 'kjyfx',
  },
  '米果动物园': <String, Object?>{
    'name': '米果动物园',
    'class': '小班',
    'describe': '社会、语言',
    'type': '童梦之语',
    'letterName': 'mgdwy',
  },
  '米果烘焙店': <String, Object?>{
    'name': '米果烘焙店',
    'class': '小班',
    'describe': '语言、社会',
    'type': '童梦之语',
    'letterName': 'mghbd',
  },
  '米果飞机场': <String, Object?>{
    'name': '米果飞机场',
    'class': '小班',
    'describe': '语言、社会',
    'type': '童梦之语',
    'letterName': 'mgfjc',
  },
  '细菌的世界': <String, Object?>{
    'name': '细菌的世界',
    'class': '大班',
    'describe': '科学、健康',
    'type': '自然之谜',
    'letterName': 'xjdsj',
  },
  '自我保护': <String, Object?>{
    'name': '自我保护',
    'class': '大班',
    'describe': '健康、社会',
    'type': '安全之盾',
    'letterName': 'zwbh',
  },
  '节奏与律动': <String, Object?>{
    'name': '节奏与律动',
    'class': '大班',
    'describe': '艺术',
    'type': '音乐之声',
    'letterName': 'jzyld',
  },
  '英文绘本': <String, Object?>{
    'name': '英文绘本',
    'class': '大班',
    'describe': '语言',
    'type': '创想之光',
    'letterName': 'ywhb',
  },
  '规律大探秘': <String, Object?>{
    'name': '规律大探秘',
    'class': '大班',
    'describe': '社会、语言',
    'type': '智慧之力',
    'letterName': 'gldtm',
  },
  '讲卫生不生病': <String, Object?>{
    'name': '讲卫生不生病',
    'class': '小班',
    'describe': '健康、科学、社会',
    'type': '内省之智',
    'letterName': 'jwsbsb',
  },
  '调皮的球': <String, Object?>{
    'name': '调皮的球',
    'class': '中班',
    'describe': '健康、社会',
    'type': '运动之星',
    'letterName': 'tpdq',
  },
  '趣味交通': <String, Object?>{
    'name': '趣味交通',
    'class': '全部年级',
    'describe': '社会',
    'type': '安全之盾',
    'letterName': 'qwjt',
  },
  '跳动的小音符': <String, Object?>{
    'name': '跳动的小音符',
    'class': '大班',
    'describe': '艺术',
    'type': '音乐之声',
    'letterName': 'tddxyf',
  },
  '身体的奥秘': <String, Object?>{
    'name': '身体的奥秘',
    'class': '大班',
    'describe': '健康、科学',
    'type': '内省之智',
    'letterName': 'stdam',
  },
  '遇到火灾我不慌': <String, Object?>{
    'name': '遇到火灾我不慌',
    'class': '全部年级',
    'describe': '健康、科学',
    'type': '安全之盾',
    'letterName': 'ydhzwbh',
  },
  '闪亮的国粹': <String, Object?>{
    'name': '闪亮的国粹',
    'class': '中班',
    'describe': '社会、艺术、语言',
    'type': '创想之光',
    'letterName': 'sldgc',
  },
  '闪亮的大眼睛': <String, Object?>{
    'name': '闪亮的大眼睛',
    'class': '中班',
    'describe': '健康、科学',
    'type': '内省之智',
    'letterName': 'slddyj',
  },
  '风的奥秘': <String, Object?>{
    'name': '风的奥秘',
    'class': '中班',
    'describe': '科学、社会',
    'type': '自然之谜',
    'letterName': 'fdam',
  },
};